SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS product_goods_channel_binding (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '绑定ID',
  goods_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  platform_account_id BIGINT UNSIGNED NOT NULL COMMENT '渠道账号ID',
  supplier_goods_no VARCHAR(128) NOT NULL COMMENT '对接商品编号',
  supplier_goods_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '对接商品名称',
  source_cost_price DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '原始进货价',
  cost_price DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '比较成本价',
  tax_adjust_direction VARCHAR(32) NOT NULL DEFAULT 'none' COMMENT '税额调整方向',
  tax_adjust_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '税率',
  tax_adjust_amount DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '税额调整值',
  dock_status TINYINT NOT NULL DEFAULT 1 COMMENT '对接状态',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序值',
  order_weight DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '下单权重',
  order_time_start VARCHAR(5) NULL COMMENT '下单开始时段',
  order_time_end VARCHAR(5) NULL COMMENT '下单结束时段',
  validate_template_id BIGINT UNSIGNED NULL COMMENT '充值模板ID',
  is_auto_change TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用自动改价',
  add_type VARCHAR(16) NOT NULL DEFAULT '' COMMENT '自动改价类型',
  default_price DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '利润值',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_at DATETIME NULL COMMENT '删除时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_product_goods_channel_binding_active (goods_id, platform_account_id, supplier_goods_no, is_deleted),
  KEY idx_product_goods_channel_binding_goods (goods_id, is_deleted, sort, id),
  KEY idx_product_goods_channel_binding_platform (platform_account_id, is_deleted, id)
) COMMENT='商品渠道绑定表';
