SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS external_order (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '订单ID',
  order_no VARCHAR(40) NOT NULL COMMENT '订单号',
  goods_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  goods_code VARCHAR(32) NOT NULL COMMENT '商品编码快照',
  goods_name VARCHAR(255) NOT NULL COMMENT '商品名称快照',
  goods_type VARCHAR(32) NOT NULL COMMENT '商品类型快照',
  supply_type VARCHAR(32) NOT NULL COMMENT '供货方式快照',
  subject_id BIGINT UNSIGNED NULL COMMENT '商品主体ID快照',
  subject_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '商品主体名称快照',
  has_tax TINYINT NOT NULL DEFAULT 0 COMMENT '商品含税快照',
  account VARCHAR(255) NOT NULL COMMENT '充值账号',
  quantity INT NOT NULL COMMENT '购买数量',
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '下单单价',
  order_amount DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '订单金额',
  cost_amount DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '成本金额',
  profit_amount DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '利润金额',
  status VARCHAR(32) NOT NULL COMMENT '订单状态',
  current_attempt_id BIGINT UNSIGNED NULL COMMENT '当前尝试ID',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT '尝试次数',
  last_receipt VARCHAR(512) NOT NULL DEFAULT '' COMMENT '最近回执',
  next_poll_at DATETIME NULL COMMENT '下次查单时间',
  last_poll_at DATETIME NULL COMMENT '最近查单时间',
  poll_count INT NOT NULL DEFAULT 0 COMMENT '查单次数',
  last_poll_error VARCHAR(512) NOT NULL DEFAULT '' COMMENT '最近查单异常',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_external_order_order_no (order_no),
  KEY idx_external_order_status_poll (status, next_poll_at, id),
  KEY idx_external_order_created (created_at, id),
  KEY idx_external_order_goods (goods_id, created_at),
  KEY idx_external_order_account (account, created_at)
) COMMENT='外部订单主表';

CREATE TABLE IF NOT EXISTS external_order_attempt (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '尝试ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  order_no VARCHAR(40) NOT NULL COMMENT '订单号',
  attempt_no INT NOT NULL COMMENT '尝试序号',
  channel_binding_id BIGINT UNSIGNED NOT NULL COMMENT '商品渠道绑定ID',
  platform_account_id BIGINT UNSIGNED NOT NULL COMMENT '平台账号ID',
  platform_account_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '平台账号名称快照',
  platform_subject_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '平台账号主体ID快照',
  platform_subject_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '平台账号主体名称快照',
  provider_code VARCHAR(32) NOT NULL COMMENT '适配器编码',
  supplier_goods_no VARCHAR(128) NOT NULL COMMENT '上游商品编号',
  supplier_goods_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '上游商品名称快照',
  supplier_us_order_no VARCHAR(64) NOT NULL COMMENT '上游商家单号',
  supplier_order_no VARCHAR(128) NOT NULL DEFAULT '' COMMENT '上游订单号',
  supplier_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '上游原始状态',
  refund_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '上游退款状态',
  request_snapshot TEXT NOT NULL COMMENT '请求快照',
  response_snapshot TEXT NOT NULL COMMENT '响应快照',
  receipt VARCHAR(512) NOT NULL DEFAULT '' COMMENT '上游回执',
  status VARCHAR(32) NOT NULL COMMENT '尝试状态',
  submitted_at DATETIME NULL COMMENT '提交时间',
  last_checked_at DATETIME NULL COMMENT '最近查单时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_external_order_attempt_order_no (order_id, attempt_no),
  UNIQUE KEY uk_external_order_attempt_supplier_us (provider_code, supplier_us_order_no),
  KEY idx_external_order_attempt_order (order_id, id),
  KEY idx_external_order_attempt_platform (platform_account_id, created_at)
) COMMENT='外部订单渠道尝试表';

CREATE TABLE IF NOT EXISTS external_order_attempt_segment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '尝试子单ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  attempt_id BIGINT UNSIGNED NOT NULL COMMENT '尝试ID',
  segment_no INT NOT NULL COMMENT '子单序号',
  quantity INT NOT NULL COMMENT '子单数量',
  provider_code VARCHAR(32) NOT NULL COMMENT '适配器编码',
  supplier_goods_no VARCHAR(128) NOT NULL COMMENT '上游商品编号',
  supplier_us_order_no VARCHAR(80) NOT NULL COMMENT '上游商家单号',
  supplier_order_no VARCHAR(128) NOT NULL DEFAULT '' COMMENT '上游订单号',
  supplier_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '上游原始状态',
  refund_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '上游退款状态',
  request_snapshot TEXT NOT NULL COMMENT '请求快照',
  response_snapshot TEXT NOT NULL COMMENT '响应快照',
  receipt VARCHAR(512) NOT NULL DEFAULT '' COMMENT '上游回执',
  status VARCHAR(32) NOT NULL COMMENT '子单状态',
  submitted_at DATETIME NULL COMMENT '提交时间',
  last_checked_at DATETIME NULL COMMENT '最近查单时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_external_order_attempt_segment_no (attempt_id, segment_no),
  UNIQUE KEY uk_external_order_segment_supplier_us (provider_code, supplier_us_order_no),
  KEY idx_external_order_segment_attempt (attempt_id, id),
  KEY idx_external_order_segment_order (order_id, id)
) COMMENT='外部订单渠道尝试子单表';

CREATE TABLE IF NOT EXISTS recharge_risk_rule (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '风控规则ID',
  account VARCHAR(255) NOT NULL COMMENT '充值账号',
  goods_keyword VARCHAR(255) NOT NULL COMMENT '商品名关键词',
  reason VARCHAR(512) NOT NULL DEFAULT '' COMMENT '风控原因',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
  hit_count INT NOT NULL DEFAULT 0 COMMENT '累计拦截次数',
  created_by_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID快照',
  created_by_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人名称快照',
  updated_by_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID快照',
  updated_by_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人名称快照',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
  deleted_at DATETIME NULL COMMENT '删除时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  UNIQUE KEY uk_recharge_risk_rule_active (account, goods_keyword, is_deleted),
  KEY idx_recharge_risk_rule_match (account, status, is_deleted, id),
  KEY idx_recharge_risk_rule_keyword (goods_keyword, is_deleted, id),
  KEY idx_recharge_risk_rule_status (status, is_deleted, updated_at)
) COMMENT='充值账号风控规则表';

CREATE TABLE IF NOT EXISTS recharge_risk_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '拦截记录ID',
  rule_id BIGINT UNSIGNED NOT NULL COMMENT '命中规则ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  order_no VARCHAR(40) NOT NULL COMMENT '订单号',
  account VARCHAR(255) NOT NULL COMMENT '充值账号',
  goods_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID快照',
  goods_code VARCHAR(32) NOT NULL COMMENT '商品编码快照',
  goods_name VARCHAR(255) NOT NULL COMMENT '商品名称快照',
  matched_keyword VARCHAR(255) NOT NULL COMMENT '命中关键词快照',
  reason VARCHAR(512) NOT NULL COMMENT '风控原因快照',
  request_token_masked VARCHAR(64) NOT NULL DEFAULT '' COMMENT '开放下单token脱敏快照',
  intercepted_at DATETIME NOT NULL COMMENT '拦截时间',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  KEY idx_recharge_risk_record_account (account, intercepted_at, id),
  KEY idx_recharge_risk_record_keyword (matched_keyword, intercepted_at, id),
  KEY idx_recharge_risk_record_rule (rule_id, intercepted_at, id),
  KEY idx_recharge_risk_record_order (order_no)
) COMMENT='充值账号风控拦截记录表';
